name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t sundarsharmaspk2023/node-devops-template .

    - name: Push to Docker Hub
      run: docker push sundarsharmaspk2023/node-devops-template:latest
